#pragma once

const int WINDOW_WIDTH_GUI = 750;
const int WINDOW_HEIGHT_GUI = 700;

const int WINDOW_WIDTH_GAME = 1000; 
const int WINDOW_HEIGHT_GAME = 1000; 

const int MUTATION_RATE = 3;

int ORGANISM_SIZE = 8;
int ORGANISM_SPEED = 1;

int ORGANISM_MAX_SIZE = 10;
int ORGANISM_MAX_SPEED = 10;

int NUMBER_OF_ORGANISMS = 50;
int NUMBER_OF_FOOD = 5500;
int NUMBER_OF_LINES = 7;
int NUMBER_OF_ANTIBIOTIC = 1000;

int ORGANISM_ENERGY = 200;
int REPRODUCTION_ENERGY = 300;
int FOOD_ENERGY = 5;
int ANTIBIOTIC_ENERGY = -3;
const int ANTIBIOTIC_SIZE = 2;
const int FOOD_SIZE = 2;

int SPAWN_RATE = 25;
int RANDOM_SPAWN_RATE = 7;
int ANTIBIOTIC_SPAWN_RATE = 20;

int GAME_SPEED_MULTIPLIER = 4;

int MAP = 1;

int GAME_SPEED = 32;

int AMOUNT_OF_GRID_CELLS = 66;

int CHANCE_OF_MUTATION = 10;
